title: Abtechnow
description: Andres Bernal -abtechnow
author: Andres Bernal
github: https://github.com/soyandresbernal
about: I'm Programmer for  .js/.rb/.py.
disqus_shortname: soyandresbernal
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/abtechnow"
    - icon: fa-twitter
      link: "https://twitter.com/AndresCarlsen"
    - icon: fa-instagram
      link: "https://www.instagram.com/abtechnow"
    - icon: fa-github
      link: "https://github.com/soyandresbernal"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

    

url: "https://soyandresbernal.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

plugins:
  - jekyll-paginate
paginate: 5
